pipeline {
    agent any
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/anantha3267/Python.git'
            }
        }

        stage('Build and Push Docker') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'd0a1f0d1-d988-4519-9391-886b74bbb920', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                        echo 'Building and pushing Docker image'
                        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                        # Change to the django folder before building the Docker image
                        cd FlaskApp
                        docker build -t anantha3267/flaskapp:${IMAGE_TAG} .
                        docker push anantha3267/flaskapp:${IMAGE_TAG}
                        '''
                    }
                }
            }
        }

        stage('Checkout K8S manifest SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/anantha3267/k8s-cicd-yaml.git'
            }
        }

        stage('Update K8S manifest & push to Repo') {
            steps {
                script {
                    withCredentials([string(credentialsId: '4f7a06f4-3a7a-45e6-9e6c-5ac270d7c79a', variable: 'gittoken')]) {
                        sh '''
                        echo 'Updating K8S manifest'
                        # Update the K8S manifest in the django directory
                        sed -i "s|image: anantha3267/flaskapp:.*|image: anantha3267/flaskapp:${IMAGE_TAG}|g" FlaskApp/deploy.yaml
                        git add FlaskApp/deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git push https://${gittoken}@github.com/anantha3267/k8s-cicd-yaml.git HEAD:main
                        '''
                    }
                }
            }
        }
    }
}
